### PR TITLE
UTF8 Text Display

### PR DESCRIPTION
**Pull request by MorningDemon515**

### CODE REVIEW

**Comment by MorningDemon515** [comment]
Now some examples can run!

**Comment by IndependentCommunity** [comment]
Despite the possibly large amount of work done:

1. Is not described what this pull request does.
2. This pull request breaks backward compatibility and complicates the API by forcing the user to enter the full path to the fonts, such as **"C:\Windows\Fonts\Arial.ttf"**, rather than just the font name, such as **"Arial"**. What if Windows is not installed on the C:\ drive? What if, for example, a fork is created for Linux or MacOS, how will the full path be handled? This is fundamentally wrong. Also, it is not allowed to modify existing examples, this breaks compatibility with classic Blitz3D.
3. The commit size is too large due to point 2.

**Comment by blitz-research** [comment]
I should have replied earlier sorry, but basically I agree with the points raised by @IndependentCommunity above. In particular, a new feature *can't* break existing code, it has to be 100% transparently backward compatible so no existing code - including examples! - should need to be changed.

But even if these points were addressed in a future PR, I have pretty much decided that I will not be accepting any more PR's for Blitz3D. Unfortunately, there doesn't not seem to be a way to disable PRs at github, so I'll update the README to hopefully make this clear.

I'll also add a link to your fork unless you have any objections.

**Comment by MorningDemon515** [comment]
alright

**Pull request closed without merging**
